# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ede55b01da228a8697ff366c390e56762ee2a591bd982e6e91d80b8f9f1a8e5d09f46dc47c0ab59cb57aad3e6332c5448a8e791795fd820ef1f355b7b2a9fe

test:
  secret_key_base: a5e6fc975af4824aecc49f0fe87f41d814061c3078f31e81525a0b3ceab264a82b42f58b71ee0f57f2ae8b7278cf5fd4f8229ae82b9a7b3ab48175227dbf5084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
